---
- name: Set filebeat_version to last version
  set_fact:
    filebeat_version: '{{ filebeat_last_version }}'
  when: filebeat_version.find('.x') == 1

- name: Create temporary build directory
  win_file:
    state: directory
    path: '{{ win_download_path }}'

- name: Setup path folders
  win_file:
    path: '{{ path_folder.value }}'
    state: directory
  with_dict: '{{ path }}'
  loop_control:
    loop_var: path_folder

- name: Reinstall (upgrade) filebeat
  block:
  - win_service:
      name: filebeat
      state: absent

  - win_file:
      name: '{{ win_download_path }}\filebeat.zip'
      state: absent

  - win_file:
      name: '{{ win_download_path }}/filebeat-{{ filebeat_version }}-windows-x86_64'
      state: absent

  - win_file:
      name: '{{ path.home }}'
      state: absent
  when: reinstall is defined
  
- name: Download filebeat
  win_get_url:
    url: 'https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ filebeat_version }}-windows-x86_64.zip'
    dest: '{{ win_download_path }}\filebeat.zip'
    force: false
  register: download_win_package
  until: download_win_package is succeeded

- name: Unzip filebeat
  win_unzip:
    src: '{{ win_download_path }}/filebeat.zip'
    dest: '{{ win_download_path }}'
    creates: '{{ win_download_path }}/filebeat-{{ filebeat_version }}-windows-x86_64'

- name: Copy files to home directory
  win_copy:
    src: '{{ win_download_path }}/filebeat-{{ filebeat_version }}-windows-x86_64/'
    dest: '{{ path.home }}/'
    force: false
    remote_src: true

- name: Templating filebeat configuration
  win_template:
    src: '{{ fb_path_file.src }}'
    dest: '{{ fb_path_file.dst }}'
  loop:
    - src: '{{ filebeat_template_src }}'
      dst: '{{ path.home }}\filebeat.yml'
  loop_control:
    loop_var: fb_path_file

- name: Install filebeat service with distribution script
  win_command: powershell install-service-filebeat.ps1
  args:
    chdir: '{{ path.home }}'

- name: Start filebeat service
  win_service:
    name: filebeat
    state: started
